org: fuwentay
app: extract-bg
service: extract-bg

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'ap-southeast-1'}
  ecr:
    images:
      time_series_img:
        path: ./bg_time_series/
        platform: linux/amd64
      occupation_analysis_img:
        path: ./bg_occupation_analysis/
        platform: linux/amd64
      uni_qs_img:
        path: ./uni_qs/
        platform: linux/amd64
      uni_the_img:
        path: ./uni_the/
        platform: linux/amd64
      uni_sh_img:
        path: ./uni_sh/
        platform: linux/amd64
      us_bls_img:
        path: ./us_bls/
        platform: linux/amd64
      cb_insights_img:
        path: ./cb_insights/
        platform: linux/amd64
      extract_table_img:
        path: ./extract_table/
        platform: linux/amd64            
      

functions:
  # lambda function name used for invoke
  time_series:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: time_series_img

  occupation_analysis:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: occupation_analysis_img

  uni_qs:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: uni_qs_img

  uni_the:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: uni_the_img
      
  uni_sh:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: uni_sh_img

  us_bls:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: us_bls_img

  cb_insights:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: cb_insights_img

  extract_table:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: extract_table_img